### ISSUE TITLE
[Opinion request] PySDL3 vs SDL3 for a Cython project

### ISSUE THREAD

**Issue by axeldavy** [Aermoss/PySDL3#1]
Hello there,

I'm working on a library written in Cython (DearCyGui)[https://github.com/axeldavy/DearCyGui], and I would like to use SDL3 for my project.

Your library seems a very good option for my needs as it would enable me to rely on your package for evolutions of SDL3, and avoiding providing a SDL3 dll in my project (basically relying on your project to find the system SDL3 or provide one).

On the other hand, the gil is still there for some time, and is a hindrance on interactivity. If a thread does heavy computation, the UI rendered by my library can be slow to refresh. Thus I would prefer having a way to have my render loop completly gil-free. On first sight, it would seem using pySDL3 would not enable to avoid the gil in the render loop.

Do you have any opinion on this ? Is pySDL3 a good fit for my project, or should I pick another option ?

**Comment by Aermoss** [comment]
Apologies for the late reply, but you already seem to have made the right choice. Yes, PySDL3 can provide the DLLs for you but I don't think it can fully meet your other needs at the moment.
