### ISSUE TITLE
`from .SDL_vulcan import *` missing from SDL.py

### ISSUE THREAD

**Issue by lemonJumps** [Aermoss/PySDL3#2]
Hi, I'm trying to make a vulkan app in python with sdl3, and I couldn't get any builtin sdl functions for vulcan to works.

as it turns out SDL_vulcan is not being imported and because of that the SDL_FUNC in that file is never run.

adding the import into SDL.py fixes the issue :D

**Comment by Aermoss** [comment]
Hi, The issue has been fixed in version [0.8.0b0](https://github.com/Aermoss/PySDL3/releases/tag/v0.8.0b0), where the SDL_vulkan was imported properly. Thank you for your help! :)
